<a href="https://colab.research.google.com/github/mustangakin/pytorch_learning/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
my_torch = torch.arange(12)
my_torch

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
#reshape and view
my_torch = my_torch.reshape(2,6)

In [ ]:
my_torch

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [ ]:
# Reshape if we dom't know the number of items using -1

In [ ]:
my_torch1 = torch.arange(50)
my_torch1 = my_torch1.reshape(2,-1)
my_torch1

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
         43, 44, 45, 46, 47, 48, 49]])

In [24]:
my_torch2 = torch.arange (10)
my_torch3 = my_torch2.view(2,5)

In [25]:
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [26]:
# with reshape and view they will update

In [27]:
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
my_torch2 [1] = 233
my_torch2

tensor([  0, 233,   2,   3,   4,   5,   6,   7,   8,   9])

In [30]:
my_torch3

tensor([[  0, 233,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [31]:
# Slices
my_torch4 = torch.arange(10)
my_torch4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
my_torch5 = my_torch4.reshape (5,2)
my_torch5

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [37]:
# Grab Slice
my_torch5[:,1]

tensor([1, 3, 5, 7, 9])

In [40]:
#Grab column
my_torch5 [:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [41]:
import numpy as np

In [2]:
import torch

tensor_a = torch.tensor ([1,2,3,4])
tensor_b = torch.tensor ([6,7,8,9])
tensor_a + tensor_b

tensor([ 7,  9, 11, 13])

In [3]:
# S ubtract
tensor_b - tensor_a

tensor([5, 5, 5, 5])

In [5]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 1, 2, 1])

In [6]:
# Exponents / Power
tensor_a ** tensor_b

tensor([     1,    128,   6561, 262144])

In [7]:
tensor_b ** tensor_a

tensor([   6,   49,  512, 6561])

In [8]:
# Reassignment
tensor_a += tensor_b
tensor_a

tensor([ 7,  9, 11, 13])